### ISSUE TITLE
Cyberdeck Design for the Case

### ISSUE THREAD

**Issue by beniroquai** [openUC2/openUC2_SOOP#1]
@ranranking @christiankuttke 

This thread is for us to collect design ideas for the upcoming UC2 Flow-Stop microscope. I want the screen to be inside the Lid of the Box. 

@ranranking how much would one of the boxes be at Taobao? 

Things I like:

Source: https://www.reddit.com/r/cyberDeck/comments/xhgv0m/made_the_raspberry_pi_recovery_kit_it_was_a_great/?rdt=54283
![image](https://github.com/openUC2/openUC2_SOOP/assets/4345528/04ca1627-f30c-407f-8d5e-f69094937e5c)

source: https://www.doscher.com/work-recovery-kit/
<img width="411" alt="image" src="https://github.com/openUC2/openUC2_SOOP/assets/4345528/162caa6a-4521-4e19-b35f-0d2b75677748">

Source: https://github.com/openUC2/openUC2_SOOP/issues/new
![image](https://github.com/openUC2/openUC2_SOOP/assets/4345528/ae9a791f-0b76-4d9d-9d80-786ad1a8329d)

**Comment by ranranking** [comment]
maybe like those? price will be 10-20euro i think. there are a lot suppliers, need to test the quality i think
https://detail.tmall.com/item.htm?abbucket=8&id=630468849798&ns=1&priceTId=2100c80917198381149886337e0d9e&skuId=4662623523970&spm=a21n57.1.item.4.2164523cjKcrqn&utparam=%7B%22aplus_abtest%22:%22e0e6013374daf788f6ea7b1f1b4fecdc%22%7D

**Comment by beniroquai** [comment]
![IMG_20240629_170814.jpg](https://github.com/openUC2/openUC2_SOOP/assets/4345528/ba31e21d-d0a7-4d24-a258-8c6813072135)

I used this for the current version. Decent price. Enough room. What do you think? 

For the through holes I would like to have connectors for the tubing and electronics. What do you think @christiankuttke ? 12 v in?

**Comment by beniroquai** [comment]
Are there cad files available for those boxes from China? I've seen they
are somewhat standardized. Like type 2000 etc

**Comment by christiankuttke** [comment]
I assume they imitate Pelicases, which have CAD files freely available: https://www.peli.com/eu/en/professional/cad-downloads/

**Comment by christiankuttke** [comment]
Regarding connectors: I will open a new issue to collect connectors requirements and solutions.

**Comment by beniroquai** [comment]
So man Numbers. Which one is probably closest to ours? :D 
The lid's inner length scale was something like 235 mm

**Comment by christiankuttke** [comment]
The box needs to be fixed to the boat somehow. Maybe it can rest on a desk for occasional user interaction. But then it will have to be closed and pushed aside, maybe in a latching rest.

From the camera world there are: 
- Tripod quick-release plates (Manfrotto RC2, Arca dovetail)
- V-Mount battery plates
- Nato rails

**Comment by beniroquai** [comment]
@dboonz how would you like to mount one of these devices in your hypothetical boat. Are there standardized locks?

**Comment by beniroquai** [comment]
Done:
https://github.com/user-attachments/assets/48206963-3061-458f-9fe0-bf2d61b519b8
