### ISSUE TITLE
Light-source for Planktoscope 

### ISSUE THREAD

**Issue by beniroquai** [openUC2/openUC2_SOOP#11]
@christiankuttke we would need a better lightsource. Currently I use the one that you built with the LED array unused. The PWM in conjuciton with the rolling shutter causes stripe issues. 
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/4dde8777-0cf9-4bf4-90b7-a2bc06aeff23">
I may go for a smaller LED and have it on "always". Something as simple as that:
https://www.ebay.de/itm/173086816368

What do you think?

**Comment by christiankuttke** [comment]
The current LED can be controlled/dimmed by analog voltage and then it is not pulsing. Always-on can be built by bodging a resistor-divider onto the control pin. More sophisticated solution uses an analog output (DAC) of the standalone's esp32. The DAC pins 25 and 26 are available on standalone headers

**Comment by beniroquai** [comment]
True, I forgot that I actually do not use GPIO25/26 for anything but DAC :D 
So perhaps I should use it for.. well..the DAC ;)

**Comment by beniroquai** [comment]
The DAC from the esp32 does not seem to work as intended..

https://github.com/user-attachments/assets/8417ebc8-f779-4405-9105-cde8ee3f0a3e

This is a sinusoidal signal on 5V (not 12V)..

**Comment by beniroquai** [comment]
For the first round of prototypes we use the super-bright LED - because of recycling and stuff. 
What would be the future device @christiankuttke ? 
Please add this to #10
