### ISSUE TITLE
Raspberry Pi Touch Screen positioning+connection

### ISSUE THREAD

**Issue by christiankuttke** [openUC2/openUC2_SOOP#15]
Problem: The stack of Raspberry Pi Screen with the Raspberry screwed to the back of it is too high to fit in the pelicase lid. 

In my current planning, the lid will only contain the touch screen and will be connected to the Raspberry Pi inside the bottom of the Pelicase.

The Raspberry Pi's connection to the screen is a 15-pin shielded ribbon cable (DSI, in the case of the Pi 5 a Display cable standard-mini, https://www.raspberrypi.com/products/display-cable/) and 5V connection with Dupont jumpers to the GPIO of the Pi.

Reverse-engineering the **ribbon cable** reveals that there are 3 length-matched differential pairs for DSI, 3.3V, GND/Shield, SDA,SCL. A replacement cable would have to have 3 twisted pairs + 5 wires (any kind). According to Wikipedia, DSI has frequencies of MHz to GHz. (https://en.wikipedia.org/wiki/Display_Serial_Interface#Design)

Idea: Use a cable with twisted pairs like HDMI or Ethernet through openings in the inner bottom and inner lid plates to connect screen and Raspberry pi. 

HDMI has 4 twisted pairs with individual, mutually insulated shields, 5 thin wires and a bare wire that's connected to the shield. HDMI spec has a "pixel clock"/character rate of up to 600 MHz (https://en.wikipedia.org/wiki/HDMI#Main_specifications). Frequency-wise, it may work.

Ethernet: Cat. 6 cable, which we have a bunch of, is specified at 250 MHz, so it may not work to push DSI over that. (https://en.wikipedia.org/wiki/Category_6_cable)

Impedance is another thing but I'd rather try it out if it works with the HDMI cable than continue speculating on closed specs of DSI and HDMI.

**Comment by christiankuttke** [comment]
If we place the Raspberry in the lid, we'll have much more heat generation in the lid, and we'll have to route all the connections through the hinge. (USB, Ethernet, power)

**Comment by christiankuttke** [comment]
Maybe a HDMI+USB touch screen would be an option instead of the Raspberry Pi Touch Screen?

**Comment by beniroquai** [comment]
Hey @christiankuttke, that's indeed a true observation. The thickness of the screen+raspi exceed the one from the lid. 
**However**, I was able to fit everything in the box:

![image](https://github.com/user-attachments/assets/3e7df799-86e3-4f8e-83b1-5865e41043a9)

The cables will connect all USB components to the Pi. It works and doesn't get too hot. Also, I would suggest to have an external connection via Wifi see #14 to operate the device outside the box.

**Comment by beniroquai** [comment]
I'd say we can keep it the way it is. We have plenty of displays in stock, so we can reuse them. 

Current configuration:
- Raspi 5 8GB + 128GB microSD
- 7inch official Raspi Screen mipi interface
- new CSI cable

**Comment by christiankuttke** [comment]
OK. Taking the Raspberrypi position in the lid as given.

Inside the bottom of the pelicase need to be a couple of devices requiring USB: UC32 standalone (ESP32), Camera, GPS board, exposed USB ports. To prevent us having to put many USB cables through the hinge, I propose the following: 

We use a USB 3 port of the Raspi in the lid to connect a USB M.2 board for the SSD. We position this in the lid.

We solder a Ethernet or HDMI cable to the PCIe port of the Raspi 5 and route it through the hinge. PCIe for one lane uses 3 differential pairs. Ethernet cables have 4 differential pairs (https://en.wikipedia.org/wiki/Category_6_cable#Description). We could use these, and transfer 12V up to a 12V->5V buck converter in the lid through the last pair. There'll be voltage drop (thin ethernet wires) but it should be OK for the buck converter to compensate.

In the pelicase bottom, we can have a PCIe to USB shield (or similar) like this: https://www.pishop.us/product/pcie-to-usb-3-2-gen1-hat-for-raspberry-pi-5-pcie-to-usb-hub-4x-high-speed-usb-ports/ The PCIe-USB chip is PCIe Gen 2, so it should work over technically unsuitable wire (more below). In the Raspi, the PCIe breakout port has to be enabled and set to Gen 2 speed: https://www.waveshare.com/wiki/PCIe_TO_USB_3.2_Gen1_HAT+

PCIe as physical/link layer is robust, more robust than USB. So this may work elegantly and more robust than running a bunch of USB cables or a USB-to-USB hub through the hinge. Further reading: https://hackaday.com/2023/03/14/pcie-for-hackers-the-diffpair-prelude/

In the bottom of the pelicase, I would expose 2 USB ports to the user through the inside bottom surface (maybe using a USB3 hub) and connect the camera, GPS and standalone board internally inside the bottom of the pelicase. 

The PCIe-USB-shield needs 5V through its jumpers, but I think we may use this from the standalone board since this should have some leftover. We'd have to try if it glitches when connecting cheap keyboard, mouse, and external spinning HDD though.

For ethernet, to break out the Raspberrypi's on-board jack, we'll have to pull a second ethernet cable through the hinge. We could also just ship a USB to Ethernet adapter as separate accessory.

**Comment by beniroquai** [comment]
I like what you're saying. Let'S see how we get all the holes into the Box ;-)
The lid can be dismounted and placed on the CNC mill..but the rest is tricky ;)

**Comment by beniroquai** [comment]
I think we have a good solution now. Everything fits in the box and we can close the lid. It's not getting too hot 
![image](https://github.com/user-attachments/assets/5f7bc233-5a9a-48a8-b769-556a177e2e73)
![image](https://github.com/user-attachments/assets/c307fef0-82ff-424f-b415-f56e7c9f33c7)
![image](https://github.com/user-attachments/assets/80d674f9-5bba-4156-a804-89dd978a274f)
