### ISSUE TITLE
CAD - Piles inside the main body to mount the optics plate

### ISSUE THREAD

**Issue by beniroquai** [openUC2/openUC2_SOOP#16]
- [ ] Design Pillars that will be blued into the lid
- [ ] test and mount optics unit 
- [ ] @ranranking should we use magnets for quick lock
- [x] have handle bars in lid to remove the optics part easily
- [x] mount the cables somewhere

**Comment by ranranking** [comment]
mount the cables somewhere

**Comment by beniroquai** [comment]
![image](https://github.com/user-attachments/assets/02f81d51-e270-4855-9830-2265727d9118)
