### ISSUE TITLE
SOFTWARE - Add FTP Server / Gallery

### ISSUE THREAD

**Issue by beniroquai** [openUC2/openUC2_SOOP#20]
Perhaps we could add an FTP Server on the External drive to serve files to users for downloading / Displaying 

This looks cool:
https://haltakov.net/simple-photo-gallery/

@ranranking

**Comment by ranranking** [comment]
that is really nice, since they want to build the database, it will make things easier

**Comment by beniroquai** [comment]
Regarding the gallery I'm not so sure yet. Dynamic loading is not supported it seems. Also, the TIFs may be a bit complicated and computationally intense.. @christiankuttke what do you think?
For the FTP Server we can try installing it in docker and access the `/dataset` folder that is actually the externally mounted folder..

```dockerfile
# Install vsftpd
RUN apt-get update && apt-get install -y vsftpd

# Configure vsftpd
RUN echo "listen=YES" >> /etc/vsftpd.conf && \
    echo "anonymous_enable=YES" >> /etc/vsftpd.conf && \
    echo "anon_root=/dataset" >> /etc/vsftpd.conf && \
    echo "local_enable=YES" >> /etc/vsftpd.conf && \
    echo "write_enable=YES" >> /etc/vsftpd.conf && \
    echo "chroot_local_user=YES" >> /etc/vsftpd.conf && \
    echo "allow_writeable_chroot=YES" >> /etc/vsftpd.conf

# Expose FTP port
EXPOSE 21
```

**Comment by christiankuttke** [comment]
Docker bind mount of some kind is missing: https://docs.docker.com/storage/bind-mounts/

I propose referencing human-made repos/dockerfiles for common usecases.

Your previous code is identical to the first part of this: https://github.com/garethflowers/docker-ftp-server

More secure is a HTTP interface/directory listing with download. A web server like nginx can be installed on the raspberry directly and be configured to serve the directory when you to its ip. 

Alternative: direct access via ssh. If the ssh server (openssh-server) is running, you can log in to the pi with username, password, port 22 in filezilla set to ftps/ftp over ssh. That is the most elegant way

**Comment by beniroquai** [comment]
The SSH server is already running. Would be fine with that one too

**Comment by christiankuttke** [comment]
I just looked it up: SFTP is FTP-like experience over SSH. FTPS is something different and unusual.

Gallery: In Linux KDE's file browser Dolphin, I can set up a SFTP connection as network folder and then get previews and my local programs (text editor, image browser) work and save seamlessly to it. Also standard FTP.

I know that VS code has a mode like that too: [Remote-SSH extension](https://code.visualstudio.com/docs/remote/ssh) This needs a ssh client installed on the local machine, but windows actually ships with this (command-line ssh client)!

**Comment by beniroquai** [comment]
@Johannes
