### ISSUE TITLE
CAD - Make Illumination "Flipable"

### ISSUE THREAD

**Issue by beniroquai** [openUC2/openUC2_SOOP#21]
@ranranking you had this idea of sharing it away, would you like to work on that? :)

**Comment by ranranking** [comment]
sure, i will think about it

**Comment by beniroquai** [comment]
As I was already on it :-) 


![](https://github.com/user-attachments/assets/37fb3b06-3892-4d00-b4e0-3d228eef1b97)

**Comment by ranranking** [comment]
i slightly modified the part and add a endstop for vertical direction, it limits the LED go onto the chip and hopefully can keep the LED parallel to the optical axis

**Comment by beniroquai** [comment]
Perfect. Thanks!! :)
