### ISSUE TITLE
Connecting Luer Ibidi µSlide to Tubes

### ISSUE THREAD

**Issue by beniroquai** [openUC2/openUC2_SOOP#5]
Hey @ranranking do you know any good/standardized tubing system for the microslide?

**Comment by beniroquai** [comment]
@ranranking are there alternative solutions? How did You connect the tubing back then with the tweezers? Which glue would hold? Hot glue doesn't ;)

**Comment by christiankuttke** [comment]
Here is the Ibidi µ-slide Luer product information datasheet: https://ibidi.com/img/cms/products/labware/channel_slides/S_801XX_Slide_ILuer/IN_801XX_I_Luer.pdf

**Comment by christiankuttke** [comment]
> i think the tube is always standard FEP 1/8 tube i think, maybe we can try with the option from ibidi?
> 
> https://ibidi.com/flow-accessories/75-tube-adapter-set.html
> 
> https://ibidi.com/flow-accessories/68-elbow-luer-connector.html

Ibidi adapter sets or at least the elbow is for 1.6 mm tubing! (1/16" ID) It should not be used if we use 1/8" or 3 mm tubing for all of our plumbing. We can work something out and get our own Luer male fittings to connect to the ibidi slide.

**Comment by beniroquai** [comment]
Ok. Thanks @christiankuttke for all the details. I guess I get the current situation roughly. I like the Elbow connectors with the right tubing. Would you mind to make or enhance the drawing you created in the other post with part numbers and/or names? In best case all components com from one manufacturer so that we keep the BOM simple. 

From what I understand:

We start with gardina tubing from the boat-side. Then we have a bypass that will go to our system. Our system has yet another bypass where we have a "shunt" (0resistance kinda thing) and the microscope. The microscope has the chip that needs luer (1ml syringes actually work too..didn't expect it was luer..), then from luer we need a tube to the pump that requires 2x4/3x5mm tubes according to the "manufacturer" https://www.aliexpress.us/item/3256804054017181.html
From there we would need another 2x4/3x5mm tube to the T that closes the bypass. We would need the valves too.  Would you mind creating such diagram e.g. in Powerpoint or something similar and post the link here? That would be brilliant! Thanks!

**Comment by christiankuttke** [comment]
I will create a bill of material and create diagrams later this week. I will also include tubing and the adapters and fittings to make it work with gardena. 

Is our connection to the boat a single gardena connector or two (inlet/outlet)? 

If there is a continuous line where we have a single Tee off of, and if there are other measurements done with the water downstream from us, our flushing will introduce "old" water since it is stored in our box and then later used to flush our flowcell.

**Comment by beniroquai** [comment]
That's a very good question. We should get back to the Helmholtz people! 
Do you add all these information alongside the other design freeze decisions into the Readme.md? That would be great! Thanks! :)

**Comment by beniroquai** [comment]
I have ordered all the parts. Let's now go over and put the parts together once they arrive @christiankuttke.
