### ISSUE TITLE
Connectors on outside of the box

### ISSUE THREAD

**Issue by christiankuttke** [openUC2/openUC2_SOOP#7]
The box has electrical and water lines to connect it to the boat.

All cables and lines should connect to the camera box via connectors. The camera box should be able to disconnect from all lines. The box, its components and lines should not spill, dry out, or break when disconnected. Connectors presented to the outside when the box is closed should be somewhat ruggedized. 

- Electric
  - Power input
  - GPS antenna connector
- Water
  - Sample water in
  - Water output

## Questions to be determined: 

- Should the microscope run while the lid is closed? If yes:
  - No lines can be squeezed in the closed lid
  - Heat needs to be transported outside the case (Fan or Liquid cooling?)
- What protection against water and dust/particle ingress does it need? IP rating
- Is there a filtered fresh water supply suitable for liquid cooling?

**Comment by christiankuttke** [comment]
The water tubes probably use a push-to-connect fitting, which are usually without shut-off valve, but there are some available with shut-off valve: https://www.mcmaster.com/products/pneumatic-hose-fittings/

Gardena connector was mentioned: https://www.mcmaster.com/products/fittings/thread-type~ght/quick-disconnect-garden-hose-couplings/
Plugs don't have shut-off valve, but sockets are available with shut-off valve.

There are connectors typically found on excavators called "International Standard ISO Minimal-Spill Quick-Disconnect Hose Couplings for Hydraulic Fluid" which have shut-off valves in both coupling parts. https://www.mcmaster.com/products/couplings/international-standard-iso-minimal-spill-quick-disconnect-hose-couplings-for-hydraulic-fluid-9/

Maybe someone has experience with lab equipment fluid-carrying connectors.

**Comment by christiankuttke** [comment]
Industrial settings use manual shut-off valves and non-valved connectors and accept a little bit of spill on disconnect.

**Comment by beniroquai** [comment]
> ## Questions to be determined:
> * Should the microscope run while the lid is closed? If yes:
Yes. It should operate while lid is closed. Eventually we would need a fan to cool the device, too. 
>   * No lines can be squeezed in the closed lid
Exactly. Therefore we would need to drill holes for through-hole connectors. 
>   * Heat needs to be transported outside the case (Fan or Liquid cooling?)
Fan
> * What protection against water and dust/particle ingress does it need? IP rating
Good question. No IP41 or something. I'd say if the lid is closed major dust particles won't enter. I'm assuming there is no water inside the boat, so no water protection necessary
> * Is there a filtered fresh water supply suitable for liquid cooling?
Na' too complicated. Fan is good :)

Regarding Gardina, I think we will have a bypass from garden to something a lot smaller in diameter.Would you mind checking the planktoscope which one they use :) 
https://www.planktoscope.org/

**Comment by christiankuttke** [comment]
From the planktoscope paper's supplemental materials, here is the fluidic materials list: 

![Screenshot_20240702-224634.png](https://github.com/openUC2/openUC2_SOOP/assets/74929609/4771ca03-df54-4a65-9a31-7b6104566a5d)


Planktoscope uses the following: 

- Their microfluidic slide is this: https://ibidi.com/channel-slides/50--slide-i-luer.html. it has Luer female ports. That is the standardized friction-fit syringe geometry consisting of cylinder surfaces tapered at a very specific angle to eventually seal watertight and be a mechanical connection.
- The Luer female port on the slide does not have "wings" compatible with Luer Lock. They adapt it to 1.6mm ID silicone tubing with 2 Luer male to 1.6mm (ID) adapters.
- They use 1.6mm tubing to Luer Lock adapters to attach securely to the syringe. The syringe has a cylinder with inwards facing screw thread surrounding the Luer male end.


If we use Luer ports at the outside of our device, it will have to have separate manual shut-off valves in front of the Luer ports of boat and/or our box. Maybe our box doesn't drip too much when disconnected due to the peristaltic pump restricting free flow. 

Most practically the box would have female locking Luer ports for inlet and outlet (to run/purge it using syringes), but it would have to stick out and the wings would be at risk of breaking off. Maybe there is a ruggedized solution.

**Comment by beniroquai** [comment]
there is also an up-to-date BOM from the planktoscope in case of interest: https://github.com/PlanktoScope/PlanktoScope/blob/master/hardware/v2.5/bom.csv

**Comment by christiankuttke** [comment]
Design locking this with the following decisions: 

The box should work with the lid closed. Only low water ingress protection is needed.

The box should have a fan to facilitate internal air flow to carry heat outside. This should be done using a sponge and a grill, or a fine mesh over each opening. Air flow should be in one one side and out the other side. Only 1 fan is needed (pulling air out) but a fan on air inlet and outlet is better. Fans should be completely inside the box.

Boat inlet and outlet is from Gardena (gender unknown, buy both or a gender changer).

Outside the box, Gardena is adapted to Luer Lock.

Tubing used inside and outside is 3 mm ID silicone tubing. 

Fitting system is Luer Lock. The inlet and outlet to the box should be Luer Lock.

Manual stop valves (e.g. Luer Lock) close to the working place of the box prevent spilling at disconnect.

DC power shall be input into the box.

At least 2 USB ports shall be accessible from the open box (to plug in a transfer hard drive and a mouse to initiate data transfer).

GPS antenna is connected to a SMA jack on the outside of the box.

**Comment by beniroquai** [comment]
That's great! Thanks @christiankuttke! Should we add these points to the README.md?
