### ISSUE TITLE
Some Comments w.r.t. the Raspberry Pi Behaviour

### ISSUE THREAD

**Issue by beniroquai** [openUC2/openUC2_SOOP#8]
# increase swap size to 1024

# ownsership of uc2 for extenral drives

# use raspberry pi 5 

# use better power supply 

SSD 

sudo apt install onboard
sudo apt install at-spi2-core

rotate screen from start menu 

install docker 

autostart docker

**Comment by christiankuttke** [comment]
OK, I will assemble the BOM for prototype 2 around Raspberry Pi 5.

**Comment by beniroquai** [comment]
exactly. This is just a thread I have to fill later with experience for installing the software.

**Comment by beniroquai** [comment]
I have summarized all that in this repo: https://github.com/openUC2/ImSwitchDockerInstall
